baseURL: 'https://csabhayy.github.io/strollers/'
languageCode: 'en-us'
title: 'Strollers'
theme: 'PaperMod'

params:
  pprofileMode:
        enabled: true
        title: "Strollers" # optional default will be site title
        subtitle: ""
        imageUrl: "" # optional
        imageTitle: "" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
            url: "/archive"
            - name: Github
            url: "https://github.com/"

    socialIcons: # optional
        - name: "<platform>"
            url: "<link>"
        - name: "<platform 2>"
            url: "<link2>"