baseURL = 'https://csabhayy.github.io/strollers/'
languageCode = 'en-us'
title = 'Strollers'
theme = 'PaperMod'

params:
  author: Abhay Sharma
  homeInfoParams:
    Title: "the dev blog"
    Content: >
      - This space shows and guides for devs for exploring, building different backend/infra projects.
